//
// Generated file, do not edit! Created by nedtool 5.5 from lte/stack/rlc/packet/LteRlcPdu.msg.
//

#ifndef __LTERLCPDU_M_H
#define __LTERLCPDU_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif



class LteRlcPdu;
class LteRlcPduNewData;
#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

/**
 * Class generated from <tt>lte/stack/rlc/packet/LteRlcPdu.msg:22</tt> by nedtool.
 * <pre>
 * class LteRlcPdu extends inet::FieldsChunk
 * {
 *     // TODO: size 0
 *     chunkLength = inet::B(1); // TODO: should be a tag;
 *     unsigned int totalFragments;    // Total number of fragments
 *     unsigned int snoFragment;        // Sequence number of this fragment
 *     unsigned int snoMainPacket;        // ID of packet (sequence number)
 * }
 * </pre>
 */
class INET_API LteRlcPdu : public ::inet::FieldsChunk
{
  protected:
    unsigned int totalFragments = 0;
    unsigned int snoFragment = 0;
    unsigned int snoMainPacket = 0;

  private:
    void copy(const LteRlcPdu& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const LteRlcPdu&);

  public:
    LteRlcPdu();
    LteRlcPdu(const LteRlcPdu& other);
    virtual ~LteRlcPdu();
    LteRlcPdu& operator=(const LteRlcPdu& other);
    virtual LteRlcPdu *dup() const override {return new LteRlcPdu(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual unsigned int getTotalFragments() const;
    virtual void setTotalFragments(unsigned int totalFragments);
    virtual unsigned int getSnoFragment() const;
    virtual void setSnoFragment(unsigned int snoFragment);
    virtual unsigned int getSnoMainPacket() const;
    virtual void setSnoMainPacket(unsigned int snoMainPacket);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LteRlcPdu& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LteRlcPdu& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>lte/stack/rlc/packet/LteRlcPdu.msg:32</tt> by nedtool.
 * <pre>
 * // new data indication for MAC
 * class LteRlcPduNewData extends LteRlcPdu
 * {
 * }
 * </pre>
 */
class INET_API LteRlcPduNewData : public ::LteRlcPdu
{
  protected:

  private:
    void copy(const LteRlcPduNewData& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const LteRlcPduNewData&);

  public:
    LteRlcPduNewData();
    LteRlcPduNewData(const LteRlcPduNewData& other);
    virtual ~LteRlcPduNewData();
    LteRlcPduNewData& operator=(const LteRlcPduNewData& other);
    virtual LteRlcPduNewData *dup() const override {return new LteRlcPduNewData(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LteRlcPduNewData& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LteRlcPduNewData& obj) {obj.parsimUnpack(b);}

#endif // ifndef __LTERLCPDU_M_H

