//
// Generated file, do not edit! Created by nedtool 5.5 from lte/apps/alert/AlertPacket.msg.
//

#ifndef __ALERTPACKET_M_H
#define __ALERTPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif



class AlertPacket;
#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

/**
 * Class generated from <tt>lte/apps/alert/AlertPacket.msg:18</tt> by nedtool.
 * <pre>
 * class AlertPacket extends inet::FieldsChunk
 * {
 *     unsigned int sno;
 *     simtime_t payloadTimestamp;
 * }
 * </pre>
 */
class INET_API AlertPacket : public ::inet::FieldsChunk
{
  protected:
    unsigned int sno = 0;
    omnetpp::simtime_t payloadTimestamp = SIMTIME_ZERO;

  private:
    void copy(const AlertPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const AlertPacket&);

  public:
    AlertPacket();
    AlertPacket(const AlertPacket& other);
    virtual ~AlertPacket();
    AlertPacket& operator=(const AlertPacket& other);
    virtual AlertPacket *dup() const override {return new AlertPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual unsigned int getSno() const;
    virtual void setSno(unsigned int sno);
    virtual omnetpp::simtime_t getPayloadTimestamp() const;
    virtual void setPayloadTimestamp(omnetpp::simtime_t payloadTimestamp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const AlertPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, AlertPacket& obj) {obj.parsimUnpack(b);}

#endif // ifndef __ALERTPACKET_M_H

