//
// Generated file, do not edit! Created by nedtool 5.5 from lte/stack/rlc/am/packet/LteRlcAmSdu.msg.
//

#ifndef __LTERLCAMSDU_M_H
#define __LTERLCAMSDU_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif



class LteRlcAmSdu;
#include "lte/stack/rlc/packet/LteRlcSdu_m.h" // import lte.stack.rlc.packet.LteRlcSdu

/**
 * Class generated from <tt>lte/stack/rlc/am/packet/LteRlcAmSdu.msg:14</tt> by nedtool.
 * <pre>
 * class LteRlcAmSdu extends LteRlcSdu
 * {
 * }
 * </pre>
 */
class INET_API LteRlcAmSdu : public ::LteRlcSdu
{
  protected:

  private:
    void copy(const LteRlcAmSdu& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const LteRlcAmSdu&);

  public:
    LteRlcAmSdu();
    LteRlcAmSdu(const LteRlcAmSdu& other);
    virtual ~LteRlcAmSdu();
    LteRlcAmSdu& operator=(const LteRlcAmSdu& other);
    virtual LteRlcAmSdu *dup() const override {return new LteRlcAmSdu(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LteRlcAmSdu& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LteRlcAmSdu& obj) {obj.parsimUnpack(b);}

#endif // ifndef __LTERLCAMSDU_M_H

