//
// Generated file, do not edit! Created by nedtool 5.5 from lte/stack/rlc/am/packet/LteRlcAmPdu.msg.
//

#ifndef __LTERLCAMPDU_M_H
#define __LTERLCAMPDU_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif



class LteRlcAmPdu;
#include "lte/stack/rlc/LteRlcDefs_m.h" // import lte.stack.rlc.LteRlcDefs

#include "lte/stack/rlc/packet/LteRlcPdu_m.h" // import lte.stack.rlc.packet.LteRlcPdu

/**
 * Class generated from <tt>lte/stack/rlc/am/packet/LteRlcAmPdu.msg:23</tt> by nedtool.
 * <pre>
 * class LteRlcAmPdu extends LteRlcPdu
 * {
 *     \@customize(true);
 *     unsigned short amType \@enum(LteAmType);
 *     unsigned short txNumber;
 *     int firstSn;
 *     int lastSn;
 *     abstract bool bitmap[];
 * }
 * </pre>
 *
 * LteRlcAmPdu_Base is only useful if it gets subclassed, and LteRlcAmPdu is derived from it.
 * The minimum code to be written for LteRlcAmPdu is the following:
 *
 * <pre>
 * class INET_API LteRlcAmPdu : public LteRlcAmPdu_Base
 * {
 *   private:
 *     void copy(const LteRlcAmPdu& other) { ... }

 *   public:
 *     LteRlcAmPdu() : LteRlcAmPdu_Base() {}
 *     LteRlcAmPdu(const LteRlcAmPdu& other) : LteRlcAmPdu_Base(other) {copy(other);}
 *     LteRlcAmPdu& operator=(const LteRlcAmPdu& other) {if (this==&other) return *this; LteRlcAmPdu_Base::operator=(other); copy(other); return *this;}
 *     virtual LteRlcAmPdu *dup() const override {return new LteRlcAmPdu(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from LteRlcAmPdu_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(LteRlcAmPdu)
 * </pre>
 */
class INET_API LteRlcAmPdu_Base : public ::LteRlcPdu
{
  protected:
    unsigned short amType = 0;
    unsigned short txNumber = 0;
    int firstSn = 0;
    int lastSn = 0;

  private:
    void copy(const LteRlcAmPdu_Base& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const LteRlcAmPdu_Base&);
    // make constructors protected to avoid instantiation
    LteRlcAmPdu_Base();
    LteRlcAmPdu_Base(const LteRlcAmPdu_Base& other);
    // make assignment operator protected to force the user override it
    LteRlcAmPdu_Base& operator=(const LteRlcAmPdu_Base& other);

  public:
    virtual ~LteRlcAmPdu_Base();
    virtual LteRlcAmPdu_Base *dup() const override {throw omnetpp::cRuntimeError("You forgot to manually add a dup() function to class LteRlcAmPdu");}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual unsigned short getAmType() const;
    virtual void setAmType(unsigned short amType);
    virtual unsigned short getTxNumber() const;
    virtual void setTxNumber(unsigned short txNumber);
    virtual int getFirstSn() const;
    virtual void setFirstSn(int firstSn);
    virtual int getLastSn() const;
    virtual void setLastSn(int lastSn);
    virtual void setBitmapArraySize(size_t size) = 0;
    virtual size_t getBitmapArraySize() const = 0;
    virtual bool getBitmap(size_t k) const = 0;
    virtual void setBitmap(size_t k, bool bitmap) = 0;
    virtual void insertBitmap(bool bitmap) = 0;
    virtual void insertBitmap(size_t k, bool bitmap) = 0;
    virtual void eraseBitmap(size_t k) = 0;
};

#endif // ifndef __LTERLCAMPDU_M_H

