//
// Generated file, do not edit! Created by nedtool 5.5 from lte/stack/phy/packet/LteFeedbackPkt.msg.
//

#ifndef __LTEFEEDBACKPKT_M_H
#define __LTEFEEDBACKPKT_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif



class LteFeedbackPkt;
#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

/**
 * Class generated from <tt>lte/stack/phy/packet/LteFeedbackPkt.msg:12</tt> by nedtool.
 * <pre>
 * class LteFeedbackPkt extends inet::FieldsChunk
 * {
 *     chunkLength = inet::B(1); // TODO: size 0
 *     \@customize(true);  // see the generated C++ header for more info
 * }
 * </pre>
 *
 * LteFeedbackPkt_Base is only useful if it gets subclassed, and LteFeedbackPkt is derived from it.
 * The minimum code to be written for LteFeedbackPkt is the following:
 *
 * <pre>
 * class INET_API LteFeedbackPkt : public LteFeedbackPkt_Base
 * {
 *   private:
 *     void copy(const LteFeedbackPkt& other) { ... }

 *   public:
 *     LteFeedbackPkt() : LteFeedbackPkt_Base() {}
 *     LteFeedbackPkt(const LteFeedbackPkt& other) : LteFeedbackPkt_Base(other) {copy(other);}
 *     LteFeedbackPkt& operator=(const LteFeedbackPkt& other) {if (this==&other) return *this; LteFeedbackPkt_Base::operator=(other); copy(other); return *this;}
 *     virtual LteFeedbackPkt *dup() const override {return new LteFeedbackPkt(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from LteFeedbackPkt_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(LteFeedbackPkt)
 * </pre>
 */
class INET_API LteFeedbackPkt_Base : public ::inet::FieldsChunk
{
  protected:

  private:
    void copy(const LteFeedbackPkt_Base& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const LteFeedbackPkt_Base&);
    // make constructors protected to avoid instantiation
    LteFeedbackPkt_Base();
    LteFeedbackPkt_Base(const LteFeedbackPkt_Base& other);
    // make assignment operator protected to force the user override it
    LteFeedbackPkt_Base& operator=(const LteFeedbackPkt_Base& other);

  public:
    virtual ~LteFeedbackPkt_Base();
    virtual LteFeedbackPkt_Base *dup() const override {throw omnetpp::cRuntimeError("You forgot to manually add a dup() function to class LteFeedbackPkt");}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

#endif // ifndef __LTEFEEDBACKPKT_M_H

