//
// Generated file, do not edit! Created by nedtool 5.5 from lte/stack/mac/packet/LteRac.msg.
//

#ifndef __LTERAC_M_H
#define __LTERAC_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif



class LteRac;
#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

/**
 * Class generated from <tt>lte/stack/mac/packet/LteRac.msg:13</tt> by nedtool.
 * <pre>
 * class LteRac extends inet::FieldsChunk
 * {
 *     // meaningful only for DL (response) RAC packets : if true RAC request has been admitted.
 *     bool success;
 *     chunkLength = inet::B(1); // TODO: size 0
 * }
 * </pre>
 */
class INET_API LteRac : public ::inet::FieldsChunk
{
  protected:
    bool success = false;

  private:
    void copy(const LteRac& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const LteRac&);

  public:
    LteRac();
    LteRac(const LteRac& other);
    virtual ~LteRac();
    LteRac& operator=(const LteRac& other);
    virtual LteRac *dup() const override {return new LteRac(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual bool getSuccess() const;
    virtual void setSuccess(bool success);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LteRac& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LteRac& obj) {obj.parsimUnpack(b);}

#endif // ifndef __LTERAC_M_H

