//
// Generated file, do not edit! Created by nedtool 5.5 from lte/stack/pdcp_rrc/packet/LtePdcpPdu.msg.
//

#ifndef __LTEPDCPPDU_M_H
#define __LTEPDCPPDU_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif



class LtePdcpPdu;
#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

/**
 * Class generated from <tt>lte/stack/pdcp_rrc/packet/LtePdcpPdu.msg:18</tt> by nedtool.
 * <pre>
 * class LtePdcpPdu extends inet::FieldsChunk
 * {
 *     chunkLength = inet::B(1); // TODO: size 0
 * }
 * </pre>
 */
class INET_API LtePdcpPdu : public ::inet::FieldsChunk
{
  protected:

  private:
    void copy(const LtePdcpPdu& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const LtePdcpPdu&);

  public:
    LtePdcpPdu();
    LtePdcpPdu(const LtePdcpPdu& other);
    virtual ~LtePdcpPdu();
    LtePdcpPdu& operator=(const LtePdcpPdu& other);
    virtual LtePdcpPdu *dup() const override {return new LtePdcpPdu(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LtePdcpPdu& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LtePdcpPdu& obj) {obj.parsimUnpack(b);}

#endif // ifndef __LTEPDCPPDU_M_H

